/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

// Se declaran todas las funciones correspondientes a suma, resta, multiplicacion y division

float * add_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

    result = argp->num1+argp->num2; // el resultado es igual a la suma de los argumentos num1, num2
    printf("Se obtuvo solicitud : Sumando %2f y %.2f\n",argp->num1,argp->num2);
    printf("Respuesta enviada : %.2f\n", result);

	return &result;
}

// funcion sub (resta)

float * sub_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

    result = argp->num1-argp->num2;
    printf("Se obtuvo solicitud : Restando %.2f de %.2f\n", argp->num2,argp->num1);
    printf("Respuesta enviada : %.2f\n", result);

	return &result;
}

// funcion multiplicacion
//
float * mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

    result = argp->num1*argp->num2;
    printf("Se obtuvo solicitud : Multiplicando %.2f por %.2f\n", argp->num1,argp->num2);
    printf("Respuesta enviada : %.2f\n", result);


	return &result;
}

// funcion division

float * div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

    result = argp->num1/argp->num2;
    printf("Se obtuvo solicitud : Dividiendo %.2f entre %.2f\n", argp->num2,argp->num1);
    printf("Respuesta enviada : %.2f\n", result);


	return &result;
}
