/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

///funcion principal

float calculate_prog_1(char *host, float n1, float n2, char opr, CLIENT *clnt){

	float  *result_1;  // apuntador a resultado con entradas para funcion suma
	inputs  add_1_arg; // datos de entrara para suma
	float  *result_2;  // apuntador de entrada para resta
	inputs  sub_1_arg; // datos de entrara para suma
	float  *result_3;  // apuntador de entrada para multiplicacion
	inputs  mul_1_arg; // datos de entrara para multiplicacion
	float  *result_4;  // apuntador de entrada para division
	inputs  div_1_arg; // datos de entrara para division

    if(opr=='+'){
        // Si el operador ingrasdado es +, realizara las siguientes acciones
        // se agregan los valores capturados a la variable tipo input
        add_1_arg.num1=n1; //asigna el valor de n1 num1
        add_1_arg.num2=n2; //asigna el valor de n2 num2
        add_1_arg.operator=opr; //asigna el valor de opr a operator

        result_1 = add_1(&add_1_arg, clnt); // se invoca la funcion de add_1 con los parametros

        if (result_1 == (float *) NULL) { //si el resultado es igual null se muestra llamada fallida
            clnt_perror (clnt, "Llamada fallida");
        }
        return *result_1; // se retorna el valor de result_1
    }
    else if(opr=='-') {
        // Si el operador ingresad es -, realizara las siguientes acciones

        sub_1_arg.num1=n1;
        sub_1_arg.num2=n2;
        sub_1_arg.operator=opr;

        result_2 = sub_1(&sub_1_arg, clnt);
        if (result_2 == (float *) NULL) {
            clnt_perror (clnt, "Llamada fallida");
        }
        return *result_2;
    }
    else if(opr=='*') {// si el operador ingresado es *, realizara las siguientes acciones

        mul_1_arg.num1=n1;
        mul_1_arg.num2=n2;
        mul_1_arg.operator=opr;

        result_3 = mul_1(&mul_1_arg, clnt);
        if (result_3 == (float *) NULL) {
            clnt_perror (clnt, "Llamada fallida");
        }
        return *result_3;
    }
    else if(opr=='/') {// si el operador ingresado es /, realizara las siguientes acciones

        div_1_arg.num1=n1;
        div_1_arg.num2=n2;
        div_1_arg.operator=opr;

        if(n2 == 0) {// si la variable n2 es 0 mandara el siguiente mensaje
            printf("Division entre cero no es valida.\n");
            exit(0);
        }
        else { // de lo contario realizara la operacion con el siguiente codigo
            result_4 = div_1(&div_1_arg, clnt);
            if (result_4 == (float *) NULL) {
                clnt_perror (clnt, "Llamada fallida");
            }
            return *result_4;
        }
    }

}


int main (int argc, char *argv[]) {
	char *host;

    float a, b;

    char op;
    CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
    printf("Esto es una calculadora RPC para la materia sistemas distribuidos!\n"); // msj incial
    printf("+ para Suma\n - para Resta\n *para Multiplicacion\n / para division\n ");

    printf("Ingrese el 1er numero\n ");
    scanf("%f", &a);
    printf("Ingrese el 2do numero\n ");
    scanf("%f", &b);

    printf("Ingrese el operador :\n");
    scanf("%s", &op);

    host = argv[1];

    clnt= clnt_create(host, CALCULATE_PROG, CALCULATE_VER, "udp");

    if (clnt = NULL) {
        clnt_pcreateerror (host);
        exit(1);
    }

    printf("La Respuesta es = %.2f\n",calculate_prog_1(host,a,b,op,clnt));

    clnt_destroy (clnt);
    exit (0);
}
